# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  # From rev v4.1.0 upwards needs git >= 1.8.5.
  rev: v4.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace
    exclude: ^doc/_static/.*.svg

# Python linter (Flake8)
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args:
    - "--max-line-length=88"
    # E203: whitespace before ':'
    - "--ignore=E203"

# Python formatting
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black

# Python black(en) for docs
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]

# pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

# Sorted python imports
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]

## C++ formatting
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v13.0.1
  hooks:
  - id: clang-format

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: "v0.8.0.4"
  hooks:
  - id: shellcheck
